package com.softwinner.dvr.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.softwinner.dvr.dao.ImageFile;
import com.softwinner.dvr.dao.VideoFile;

import com.softwinner.dvr.dao.ImageFileDao;
import com.softwinner.dvr.dao.VideoFileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imageFileDaoConfig;
    private final DaoConfig videoFileDaoConfig;

    private final ImageFileDao imageFileDao;
    private final VideoFileDao videoFileDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imageFileDaoConfig = daoConfigMap.get(ImageFileDao.class).clone();
        imageFileDaoConfig.initIdentityScope(type);

        videoFileDaoConfig = daoConfigMap.get(VideoFileDao.class).clone();
        videoFileDaoConfig.initIdentityScope(type);

        imageFileDao = new ImageFileDao(imageFileDaoConfig, this);
        videoFileDao = new VideoFileDao(videoFileDaoConfig, this);

        registerDao(ImageFile.class, imageFileDao);
        registerDao(VideoFile.class, videoFileDao);
    }
    
    public void clear() {
        imageFileDaoConfig.clearIdentityScope();
        videoFileDaoConfig.clearIdentityScope();
    }

    public ImageFileDao getImageFileDao() {
        return imageFileDao;
    }

    public VideoFileDao getVideoFileDao() {
        return videoFileDao;
    }

}
